### ISSUE TITLE
Add Python 3 support

### ISSUE THREAD

**Issue by jorgecarleitao** [mekarpeles/captcha-decoder#5]
In Python 3, installation via pip

`pip install git+https://github.com/mekarpeles/captcha-decoder.git`

fails in line 58 of `crack_test.py` because of a `print ""`.

**Comment by mekarpeles** [comment]
The branch feature/travis branch addresses print statements, flake8 lint issues, string.lowercase -> string.ascii_lowercase and other p3 compatibility issues.

**Comment by mekarpeles** [comment]
Closed by b601288a10
