### ISSUE TITLE
commands to install support packages and libs

### ISSUE THREAD

**Issue by chicheongweng** [mekarpeles/captcha-decoder#8]
On Ubuntu 12.04 use the below commands to install support packages and libs:
sudo apt-get install libjpeg-dev
sudo apt-get install libpng-dev
pip install PIL --upgrade

**Comment by mekarpeles** [comment]
Thanks @chicheongweng ! setup.py now specifies Pillow >= 2.9.0 for installing PIL. I'll try this on a mac and windows machine and see if any additional system level packages are required and update this thread.

**Comment by mekarpeles** [comment]
Incorporated into README
